### ISSUE TITLE
Debug build crashing out of the box

### ISSUE THREAD

**Issue by RayanArnaout** [preemptive/dasho-samples#1]
Hello,

I downloaded the sample projects and tried to launch the DebuggingOnAndroid project in debug mode after setting the DASHO_HOME value. I get the following logs:

`07-13 10:04:11.554 7303-7303/com.dasho.android.debug E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.dasho.android.debug, PID: 7303
    java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{com.dasho.android.debug/com.dasho.android.debug.MainActivity}: java.lang.ClassNotFoundException: Didn't find class "com.dasho.android.debug.MainActivity" on path: DexPathList[[zip file "/data/app/com.dasho.android.debug-IVQE3WZl8pcI-pwJXx6RSA==/base.apk", zip file "/data/app/com.dasho.android.debug-IVQE3WZl8pcI-pwJXx6RSA==/split_lib_resources_apk.apk", zip file "/data/app/com.dasho.android.debug-IVQE3WZl8pcI-pwJXx6RSA==/split_lib_slice_0_apk.apk", zip file "/data/app/com.dasho.android.debug-IVQE3WZl8pcI-pwJXx6RSA==/split_lib_slice_1_apk.apk", zip file "/data/app/com.dasho.android.debug-IVQE3WZl8pcI-pwJXx6RSA==/split_lib_slice_2_apk.apk", zip file "/data/app/com.dasho.android.debug-IVQE3WZl8pcI-pwJXx6RSA==/split_lib_slice_3_apk.apk", zip file "/data/app/com.dasho.android.debug-IVQE3WZl8pcI-pwJXx6RSA==/split_lib_slice_4_apk.apk", zip file "/data/app/com.dasho.android.debug-IVQE3WZl8pcI-pwJXx6RSA==/split_lib_slice_5_apk.apk", zip file "/data/app/com.dasho.android.debug-IVQE3WZl8pcI-pwJXx6RSA==/split_lib_slice_6_apk.apk", zip file "/data/app/com.dasho.android.debug-IVQE3WZl8pcI-pwJXx6RSA==/split_lib_slice_7_apk.apk", zip file "/data/app/com.dasho.android.debug-IVQE3WZl8pcI-pwJXx6RSA==/split_lib_slice_8_apk.apk", zip file "/data/app/com.dasho.android.debug-IVQE3WZl8pcI-pwJXx6RSA==/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/com.dasho.android.debug-IVQE3WZl8pcI-pwJXx6RSA==/lib/arm64, /system/lib64, /vendor/lib64]]
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2679)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.dasho.android.debug.MainActivity" on path: DexPathList[[zip file "/data/app/com.dasho.android.debug-IVQE3WZl8pcI-pwJXx6RSA==/base.apk", zip file "/data/app/com.dasho.android.debug-IVQE3WZl8pcI-pwJXx6RSA==/split_lib_resources_apk.apk", zip file "/data/app/com.dasho.android.debug-IVQE3WZl8pcI-pwJXx6RSA==/split_lib_slice_0_apk.apk", zip file "/data/app/com.dasho.android.debug-IVQE3WZl8pcI-pwJXx6RSA==/split_lib_slice_1_apk.apk", zip file "/data/app/com.dasho.android.debug-IVQE3WZl8pcI-pwJXx6RSA==/split_lib_slice_2_apk.apk", zip file "/data/app/com.dasho.android.debug-IVQE3WZl8pcI-pwJXx6RSA==/split_lib_slice_3_apk.apk", zip file "/data/app/com.dasho.android.debug-IVQE3WZl8pcI-pwJXx6RSA==/split_lib_slice_4_apk.apk", zip file "/data/app/com.dasho.android.debug-IVQE3WZl8pcI-pwJXx6RSA==/split_lib_slice_5_apk.apk", zip file "/data/app/com.dasho.android.debug-IVQE3WZl8pcI-pwJXx6RSA==/split_lib_slice_6_apk.apk", zip file "/data/app/com.dasho.android.debug-IVQE3WZl8pcI-pwJXx6RSA==/split_lib_slice_7_apk.apk", zip file "/data/app/com.dasho.android.debug-IVQE3WZl8pcI-pwJXx6RSA==/split_lib_slice_8_apk.apk", zip file "/data/app/com.dasho.android.debug-IVQE3WZl8pcI-pwJXx6RSA==/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/com.dasho.android.debug-IVQE3WZl8pcI-pwJXx6RSA==/lib/arm64, /system/lib64, /vendor/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:125)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at android.app.Instrumentation.newActivity(Instrumentation.java:1174)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2669)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856) 
        at android.app.ActivityThread.-wrap11(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6494) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807) 
07-13 10:04:11.556 7303-7303/com.dasho.android.debug E/AndroidRuntime: 	Suppressed: java.io.IOException: No original dex files found for dex location /data/app/com.dasho.android.debug-IVQE3WZl8pcI-pwJXx6RSA==/split_lib_resources_apk.apk
        at dalvik.system.DexFile.openDexFileNative(Native Method)
        at dalvik.system.DexFile.openDexFile(DexFile.java:353)
        at dalvik.system.DexFile.<init>(DexFile.java:100)
        at dalvik.system.DexFile.<init>(DexFile.java:74)
        at dalvik.system.DexPathList.loadDexFile(DexPathList.java:374)
        at dalvik.system.DexPathList.makeDexElements(DexPathList.java:337)
        at dalvik.system.DexPathList.<init>(DexPathList.java:157)
        at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:65)
        at dalvik.system.PathClassLoader.<init>(PathClassLoader.java:64)
        at com.android.internal.os.ClassLoaderFactory.createClassLoader(ClassLoaderFactory.java:73)
        at com.android.internal.os.ClassLoaderFactory.createClassLoader(ClassLoaderFactory.java:88)
        at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:69)
        at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:35)
        at android.app.LoadedApk.createOrUpdateClassLoaderLocked(LoadedApk.java:693)
        at android.app.LoadedApk.getClassLoader(LoadedApk.java:727)
        at android.app.LoadedApk.getResources(LoadedApk.java:954)
        at android.app.ContextImpl.createAppContext(ContextImpl.java:2270)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5639)
        at android.app.ActivityThread.-wrap1(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1656)
        		... 6 more`

Building in release mode works fine.
How can I fix this problem without changing "android.buildTypes.debug.minifyEnabled true" to false ?

Thanks !

**Comment by minsko** [comment]
It appears you are encountering an issue related to Instant Run: <https://issuetracker.google.com/issues/78648628>

You should [disable](https://developer.android.com/studio/run/#disable-ir) Instant Run and try again.

**Comment by RayanArnaout** [comment]
I didn't think Instant Run would affect the project even when it is not used... Thanks a lot !
